name = "Get Todos"
version = "chuglee-1"
description = "Get Todos"
documentation = "docs/Get_Todos.md"

[http]
method = "GET"
domain = "https://jsonplaceholder.typicode.com"
path = "/todos/{{id}}"

[http.params]
id = { value = "1", description = "Todo ID" }

[http.query]
userId = { value = "1", description = "User ID", disabled = true }

[http.headers]
Accept = { value = "application/json", description = "Accept header" }
Content-Type = { disabled = true, value = "application/json", description = "Content-Type header" }

[http.body]
type = "json" # json, form, urlencoded, text, file, xml
# store form as key val pairs json
content = """
{
  "title": "foo",
  "body": "bar",
  "userId": 1
}
"""

[docs]
md = """
# Get Todos
"""
