name = "echo"
main = "index.ts"
compatibility_date = "2025-10-01"
preview_urls = false

[placement]
mode = "smart"

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
