name: Package and Release

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

permissions:
  contents: write

env:
  BINARY_NAME: Sanchaar
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux (${{ matrix.target }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            arch: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install system dependencies
        run: |
          sudo apt-get install -y \
            libssl-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libxkbcommon-dev \
            pkg-config

      - uses: Swatinem/rust-cache@v2
        with:
          key: linux-${{ matrix.target }}

      - name: Build
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            export CC=aarch64-linux-gnu-gcc
            export CXX=aarch64-linux-gnu-g++
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
            export PKG_CONFIG_ALLOW_CROSS=1
            export OPENSSL_DIR=/usr
            export OPENSSL_INCLUDE_DIR=/usr/include
            export OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
          fi
          cargo build --release --target ${{ matrix.target }} --no-default-features

      - name: Install cargo-deb
        if: matrix.arch == 'amd64'
        run: cargo install cargo-deb

      - name: Create .deb package
        if: matrix.arch == 'amd64'
        run: |
          cargo deb --target ${{ matrix.target }} --no-build --no-strip --no-default-features
          cp target/${{ matrix.target }}/debian/*.deb ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.arch }}.deb

      - name: Generate checksums
        run: |
          if [ -f "${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.arch }}.deb" ]; then
            sha256sum ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.arch }}.deb > ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.arch }}.deb.sha256
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}
          path: |
            ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.arch }}.*

  build-macos:
    name: Build macOS (${{ matrix.target }})
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            arch: Intel
          - target: aarch64-apple-darwin
            arch: AppleSilicon

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: macos-${{ matrix.target }}

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build bundle
        run: cargo bundle --release --target ${{ matrix.target }} --no-default-features

      - name: Ad-hoc code sign
        run: |
          codesign --force --deep --sign - target/${{ matrix.target }}/release/bundle/osx/${{ env.BINARY_NAME }}.app

      - name: Create DMG
        run: |
          mkdir -p dist
          cp -r target/${{ matrix.target }}/release/bundle/osx/${{ env.BINARY_NAME }}.app dist/

          # Create DMG
          hdiutil create -volname "${{ env.BINARY_NAME }}" -srcfolder dist -ov -format UDZO ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.target }}.dmg

      - name: Generate checksums
        run: |
          shasum -a 256 ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.target }}.dmg > ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.target }}.dmg.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.target }}
          path: |
            ${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.target }}.*

  release:
    name: Create Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifacts
        run: |
          mkdir release
          find artifacts -type f -exec cp {} release/ \;
          ls -lah release/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: ${{ contains(env.VERSION, 'rc') || contains(env.VERSION, 'beta') || contains(env.VERSION, 'alpha') || contains(env.VERSION, 'prerelease') }}
          generate_release_notes: true
          files: release/*
